// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9kwukuhJcKc8El2tgCoyVAKcEKyWG_4',
    appId: '1:632225016850:web:b999e9a83ec4e02e23bccb',
    messagingSenderId: '632225016850',
    projectId: 'smart-home-3d769',
    authDomain: 'smart-home-3d769.firebaseapp.com',
    storageBucket: 'smart-home-3d769.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBahoGScpPIlnByFDhhq_VI-vs_ThTwwsw',
    appId: '1:632225016850:android:c3db85b644e11d3c23bccb',
    messagingSenderId: '632225016850',
    projectId: 'smart-home-3d769',
    storageBucket: 'smart-home-3d769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7FuRzggkSv4PfFq8Gif7ivtw_KU6IZ8',
    appId: '1:632225016850:ios:503ead28f3913ef623bccb',
    messagingSenderId: '632225016850',
    projectId: 'smart-home-3d769',
    storageBucket: 'smart-home-3d769.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );
}
